### ISSUE TITLE
[Enhancement] Add a value to the QRCode Size and Image Size settings

### ISSUE THREAD

**Issue by ghost** [ffaex/event-zapper#11]
As as user, its hard to remember what size you picked for QRCode Size and Image Size. It would be more user friendly if the value is displayed next to the slider, so the user could re-use their favourite size the next time they configure an event.

Example:
<img width="1440" alt="2023-08-17_23-19-58" src="https://github.com/ffaex/event-zapper/assets/123519473/dcb70317-e015-4cd0-95e9-e93fdb53d811">

**Comment by ffaex** [comment]
Do you think it should display an additional number as in your example? Or would it be better to remove the slider altogether and just provide a text field to input a size.

**Comment by ghost** [comment]
The only downfall with text fields is that then you need to handle validation of the field (can't be blank, can't be less than, can't be more than etc.)

The real difficultly is that without some kind of live preview the user is just selecting an arbitrary number. 

Perhaps presets would be better (small, medium, large), or perhaps they don't even get the option to change QRCode and Image size, and layout sizes are determine purely by number of speakers? Thinking out loud.

**Comment by ffaex** [comment]
yes, I have thought of that as well, but I thought that because of different screen sizes at events that might become an issue. 

Maybe it should just have better default values? And we could still leave the possibility to adjust, if the qr code is unreadable on certain displays?

**Comment by ghost** [comment]
Perhaps! I have no reason to believe the current defaults are bad though, actually they seem pretty sensible. I am yet to test this on a projector size screen though, I guess I should try that! 🙂
