### ISSUE TITLE
Add "Event Zapper" title somewhere on Session Setup screen

### ISSUE THREAD

**Issue by ghost** [ffaex/event-zapper#14]
Users initially land on the Session Setup screen when visiting the site, but there's nothing telling them what app they're using. You could add the title "⚡️ Event Zapper" somewhere on the page to make it clearer.

<img width="1554" alt="2023-08-17_23-18-32 copy" src="https://github.com/ffaex/event-zapper/assets/123519473/d21fac0c-cad5-42ce-9d74-5f8842f95b34">

**Comment by ffaex** [comment]
great idea! added in the most recent commit.
