### ISSUE TITLE
[Enhancement] Open presentation view in new tab or window

### ISSUE THREAD

**Issue by ghost** [ffaex/event-zapper#3]
As an event organizer or AV person it will probably be more useful to have the presentation view open in a new tab or window when the user clicks "Present". This will make it easier for the presentation window to be dragged or streamed on a separate screen or  projector (or however the event zapper is being displayed at the event). 

This will have the added bonus of allowing the event organizer or AV person to keep the current session configuration open, incase they need to reset or re-configure it for the next set of speakers.

![present_new_window](https://github.com/ffaex/event-zapper/assets/123519473/5da9ec81-03f2-47e0-8c50-13cb60b81b46)

**Comment by owen543** [comment]
I will pay a bounty of 15k sats for this one
