### ISSUE TITLE
[Enhancement] Make it clearer if the speaker is donating Zaps to another nostr profile

### ISSUE THREAD

**Issue by ghost** [ffaex/event-zapper#4]
Currently, if a donation npub is specified in the session setup, when entering presentation view, it's not made clear to viewers that the QR code / Zaps will be funnelled towards a different nostr profile 

If a donation npub is specified in the session setup we should clearly communicate that zaps are being donated (see example in screenshot) to avoid viewer confusion.

![Untitled](https://github.com/ffaex/event-zapper/assets/123519473/a5413f6f-ee50-4fa8-bd0a-71f3680ee8fa)

**Comment by owen543** [comment]
I will pay a bounty of 15k sats for this one
