### ISSUE TITLE
[Feature] Session Presets

### ISSUE THREAD

**Issue by ghost** [ffaex/event-zapper#7]
As an event organizer, I may want to configure event zapper in advance, in preparation for numerous combinations of speakers.

Rough idea:

Session setup screen can use a tabbed approach. Clicking "+" adds an additional preset. The user can switch between different session presets using the tabs at the top of the page

<img width="1196" alt="Screenshot 2023-07-21 at 23 06 56" src="https://github.com/ffaex/event-zapper/assets/123519473/1ffe5cc2-7449-472b-be11-0081c89d707c">

<img width="1196" alt="Screenshot 2023-07-21 at 23 06 56 copy" src="https://github.com/ffaex/event-zapper/assets/123519473/c4e06dc6-2668-461a-b883-cc9da1539163">

**Comment by owen543** [comment]
I will pay a bounty of 25k sats for this one
